wait: 60
log: log/thin.log
max_persistent_conns: 512
environment: production
daemonize: true
require: []
pid: tmp/pids/thin.pid
chdir: /home/ubuntu/data/HERE/current
max_conns: 1024
timeout: 30
address: 0.0.0.0
#port: 80
#servers: 1
servers: 2
port: 3000
