default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Math-Support-Matrix_development
  username: vagrant
  password: vagrant

test:
  <<: *default
  database: Math-Support-Matrix_test
  username: vagrant
  password: vagrant

production:
  <<: *default
  database: Math-Support-Matrix
  username: vagrant
  password: vagrant
