# Ansible managed: /ansible/roles/postgresql/templates/database.yml.j2 modified on 2015-06-06 18:46:12 by vagrant on localhost

default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: Math-Support-Matrix

  username: vagrant
  password: None

test:
  <<: *default
  database: Math-Support-Matrix_test
